name: renovate
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: renovate
        uses: renovatebot/github-action@v21.33.2
        with:
          configurationFile: src/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
