name: renovate
on:
  schedule:
    - cron: '0/10 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1

      - name: setup node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      - name: renovate
        uses: renovatebot/github-action@v21.33.2
        with:
          configurationFile: renovate.config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
